export const enum FoveaDiagnosticKind {
	UNKNOWN_SELECTOR = 100,
	AMBIGUOUS_HOST = 200,

	CUSTOM_ELEMENT_MUST_EXTEND_HTML_ELEMENT = 300,
	INVALID_CUSTOM_ELEMENT_DECORATOR_CLASS_MUST_NOT_BE_ABSTRACT = 400,
	INVALID_CUSTOM_ATTRIBUTE_DECORATOR_CLASS_MUST_NOT_BE_ABSTRACT = 500,

	INVALID_CUSTOM_ELEMENT_DECORATOR_NOT_STATICALLY_ANALYZABLE = 600,
	INVALID_CUSTOM_ELEMENT_DECORATOR_NOT_CALLED = 700,
	INVALID_CUSTOM_ELEMENT_DECORATOR_NO_ARGUMENTS = 800,
	INVALID_CUSTOM_ELEMENT_DECORATOR_FIRST_ARGUMENT_MUST_BE_A_STRING = 900,
	INVALID_CUSTOM_ELEMENT_DECORATOR_PLACEMENT = 1000,

	INVALID_CUSTOM_ATTRIBUTE_DECORATOR_NOT_STATICALLY_ANALYZABLE = 1100,
	INVALID_CUSTOM_ATTRIBUTE_DECORATOR_NOT_CALLED = 1200,
	INVALID_CUSTOM_ATTRIBUTE_DECORATOR_NO_ARGUMENTS = 1300,
	INVALID_CUSTOM_ATTRIBUTE_DECORATOR_FIRST_ARGUMENT_MUST_BE_A_STRING = 1400,
	INVALID_CUSTOM_ATTRIBUTE_DECORATOR_PLACEMENT = 1500,

	INVALID_STYLE_SRC_DECORATOR_USAGE = 1600,
	INVALID_TEMPLATE_SRC_DECORATOR_USAGE = 1700,
	INVALID_ON_CHANGE_DECORATOR_USAGE = 1800,
	INVALID_LISTENER_DECORATOR_USAGE = 1900,
	INVALID_VISIBILITY_OBSERVER_DECORATOR_USAGE = 2000,
	INVALID_CHILD_LIST_OBSERVER_DECORATOR_USAGE = 2100,
	INVALID_DEPENDS_ON_DECORATOR_USAGE = 2200,
	INVALID_HOST_ATTRIBUTES_DECORATOR_USAGE = 2300,
	ONLY_LITERAL_VALUES_SUPPORTED_HERE = 2400,
	INVALID_ATTRIBUTE_OBSERVER_DECORATOR_USAGE = 2500,

	UNRESOLVED_STYLE_SRC = 2600,
	UNRESOLVED_TEMPLATE_SRC = 2700,

	INVALID_SELECTOR_NEEDS_HYPHEN = 2800,
	INVALID_SELECTOR_HAS_WHITESPACE = 2900,
	INVALID_SELECTOR_IS_NOT_ALL_LOWER_CASE = 3000,

	INVALID_CSS = 3100,
	INVALID_TEMPLATE = 3200
}