import {isClassDeclaration, isEnumDeclaration, isFunctionDeclaration, isInterfaceDeclaration, isTypeAliasDeclaration, isVariableStatement, Node, SyntaxKind} from "typescript";
import {visitVariableStatementWithExportModifier} from "./visit-variable-statement-with-export-modifier";
import {visitFunctionDeclarationWithExportModifier} from "./visit-function-declaration-with-export-modifier";
import {visitTypeAliasDeclarationWithExportModifier} from "./visit-type-alias-declaration-with-export-modifier";
import {visitInterfaceDeclarationWithExportModifier} from "./visit-interface-declaration-with-export-modifier";
import {visitClassDeclarationWithExportModifier} from "./visit-class-declaration-with-export-modifier";
import {visitEnumDeclarationWithExportModifier} from "./visit-enum-declaration-with-export-modifier";
import {DEBUG} from "../../../../constant/constant";
import {VisitorOptions} from "./visitor-options";

/**
 * Visits a Node that has an export modifier in front of it. Basically, it will remove it if it isn't
 * included in the actual output of the Chunk generated by Rollup - unless it is referenced by
 * something else within the program
 * @param {VisitorOptions<Node>} options
 * @returns {Node | undefined}
 */
export function visitNodeWithExportModifier ({node, ...rest}: VisitorOptions<Node>): Node|undefined {

	if (isVariableStatement(node)) {
		return visitVariableStatementWithExportModifier({node, ...rest});
	}
	else if (isFunctionDeclaration(node)) {
		return visitFunctionDeclarationWithExportModifier({node, ...rest});
	}
	else if (isTypeAliasDeclaration(node)) {
		return visitTypeAliasDeclarationWithExportModifier({node, ...rest});
	}
	else if (isInterfaceDeclaration(node)) {
		return visitInterfaceDeclarationWithExportModifier({node, ...rest});
	}
	else if (isClassDeclaration(node)) {
		return visitClassDeclarationWithExportModifier({node, ...rest});
	}
	else if (isEnumDeclaration(node)) {
		return visitEnumDeclarationWithExportModifier({node, ...rest});
	}

	if (DEBUG) {
		console.log("visitNodeWithExportModifier:", SyntaxKind[node.kind]);
	}

	return node;
}
